image: xefiji:latest

stages:
    - deploy


deploy:
    stage: deploy
    script:
        - python -V
        - echo $CURRENT_DIR
        - ls -la


before_script:
  #- which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - CURRENT_DIR=$(pwd)
  - whoami

after_script:
  - chown -Rf xefiji:xefiji $CURRENT_DIR/*
  - chmod 755 $CURRENT_DIR*
  - rm -rf $CURRENT_DIR/.git $CURRENT_DIR/.gitlab-ci.yml