image: python:latest

stages:
    - deploy


deploy:
    stage: deploy
    script:
        - python -V
        - pwd
        - ls -la

before_script:
  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  -chown -Rf xefiji *