image: xefiji:latest

stages:
    - deploy


deploy:
    stage: deploy
    script:
        - python -V
        - pwd
        - ls -la


before_script:
  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  #- which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - whoami

after_script:
  - chown -Rf xefiji:xefiji *
  - chmod 755 *
  - rm -rf .git .gitlab-ci.yml