image: python:latest

stages:
    - deploy


deploy:
    stage: deploy
    script:
        - python -V
        - pwd
        - ls -la
        - docker cp * /home/xefiji/builds/


#before_script:
    #- apt-get update